# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/throwaway6',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/throwaway6',
                'lib_path': 'throwaway6'},
  'syms': { 'throwaway6.core': { 'throwaway6.core.cache_data': ('core.html#cache_data', 'throwaway6/core.py'),
                                 'throwaway6.core.sample_from_spreadsheet': ('core.html#sample_from_spreadsheet', 'throwaway6/core.py')},
            'throwaway6.genericsample': { 'throwaway6.genericsample.cache_data': ('core.html#cache_data', 'throwaway6/genericsample.py'),
                                          'throwaway6.genericsample.sample_from_spreadsheet': ( 'core.html#sample_from_spreadsheet',
                                                                                                'throwaway6/genericsample.py')}}}