# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/throwaway6',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/throwaway6',
                'lib_path': 'throwaway6'},
  'syms': {'throwaway6.core': {'throwaway6.core.foo': ('core.html#foo', 'throwaway6/core.py')}}}